import Sidebar from './components/Sidebar'

export const metadata = {
  title: 'Users App',
  description: 'Generated by Next.js'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='es'>
      <body>
        <Sidebar />
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
